### ISSUE TITLE
run-puma.sh error

### ISSUE THREAD

**Issue by altman87120** [csc/Hanlon#315]
Hi，I am not much familiar with ruby. And I fellow your guid found this error happened.

* Version 2.11.0 (ruby 1.9.3-p551), codename: Intrepid Squirrel
* Min threads: 0, max threads: 16
* Environment: development
! Unable to load application: NoMethodError: undefined method `is_db_selected?' for nil:NilClass
/opt/hanlon/web/application.rb:7:in `block in <top (required)>': uninitialized constant Hanlon::WebService::App (NameError)
/opt/hanlon/core/persist/controller.rb:57:in `is_connected?': undefined method `is_db_selected?' for nil:NilClass (NoMethodError)
	from /opt/hanlon/core/persist/controller.rb:65:in `check_connection'
	from /opt/hanlon/core/data.rb:27:in `check_init'
	from /opt/hanlon/core/object.rb:65:in `get_data'
	from /opt/hanlon/core/slice.rb:34:in `initialize'
	from /opt/hanlon/core/slice/model.rb:18:in `initialize'
	from /opt/hanlon/web/api/api_model_v1.rb:15:in `new'
	from /opt/hanlon/web/api/api_model_v1.rb:15:in `<class:APIv1>'
	from /opt/hanlon/web/api/api_model_v1.rb:10:in `<module:Model>'
	from /opt/hanlon/web/api/api_model_v1.rb:8:in `<module:WebService>'
	from /opt/hanlon/web/api/api_model_v1.rb:7:in `<module:Hanlon>'
	from /opt/hanlon/web/api/api_model_v1.rb:6:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/hanlon/web/application.rb:57:in `block in <top (required)>'
	from /opt/hanlon/web/application.rb:55:in `glob'
	from /opt/hanlon/web/application.rb:55:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from config.ru:1:in `block in <main>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/lib/ruby/gems/1.9.1/gems/puma-2.11.0/lib/puma/configuration.rb:107:in `app'
	from /usr/local/lib/ruby/gems/1.9.1/gems/puma-2.11.0/lib/puma/runner.rb:113:in `load_and_bind'
	from /usr/local/lib/ruby/gems/1.9.1/gems/puma-2.11.0/lib/puma/single.rb:79:in `run'
	from /usr/local/lib/ruby/gems/1.9.1/gems/puma-2.11.0/lib/puma/cli.rb:507:in `run'
	from /usr/local/lib/ruby/gems/1.9.1/gems/puma-2.11.0/bin/puma:10:in `<top (required)>'
	from /usr/local/bin/puma:23:in `load'
	from /usr/local/bin/puma:23:in `<main>'

and this is my configuration file

--- !ruby/object:ProjectHanlon::Config::Server
noun: config
admin_port: 8025
api_port: 8026
api_version: v1
base_path: /hanlon/api
daemon_min_cycle_time: 30
force_mk_uuid: ''
hanlon_log_level: Logger::ERROR
hanlon_server: 10.0.2.15
hanlon_subnets: 10.0.2.0/24
hnl_mk_boot_debug_level: Logger::ERROR
hnl_mk_boot_kernel_args: ''
image_path: /opt/hanlon/image
ipmi_password: ''
ipmi_username: ''
ipmi_utility: ''
mk_checkin_interval: 60
mk_checkin_skew: 5
mk_gem_mirror: http://localhost:2158/gem-mirror
mk_gemlist_uri: /gems/gem.list
mk_kmod_install_list_uri: /kmod-install-list
mk_log_level: Logger::ERROR
mk_tce_install_list_uri: /tce-install-list
mk_tce_mirror: http://localhost:2157/tinycorelinux
node_expire_timeout: 300
persist_dbname: 'hanlon'
persist_host: 127.0.0.1
persist_mode: 'postgresql'
persist_password: 'hanlon'
persist_port: 5432
persist_timeout: 10
persist_username: 'hanlon'
register_timeout: 120
sui_allow_access: 'true'
sui_mount_path: /docs

**Comment by altman87120** [comment]
I found error log says:

[root@localhost web]# tail -f log/project_hanlon.log
E, [2015-02-01T21:01:16.840755 #14609] ERROR -- /opt/hanlon/core/persist/controller.rb:41:in `initialize'>>ProjectHanlon::Persist::Controller#initialize: Invalid Database plugin(postgresql)

**Comment by toepi** [comment]
Not sure, if this error occure if pq gem is not installed. But give it a try.

If you use gem install, you need postgres header (libpq-dev) also.

**Comment by tjmcs** [comment]
Actually, I think the real issue here is the `persist_mode` that you've declared in your configuration. The supported modes are `mongo` (for those who use MongoDB, which is the default backing store for Hanlon), `postgres` (to use PostgreSQL as the backing store), or `memory` (to use an 'in-memory database' as the backing store). Unfortunately, you've specified `postgresql`, not `postgres`, and Hanlon is throwing an error because it can't find a driver to use based on that `persist_mode`. Perhaps the error handling code for this case needs to be modified a bit to make the error easier to interpret, but that's the real issue (that you've declared an unsupported `persist_mode` in your Hanlon configuration).

As an aside (and in response to the previous comment by @toepi), we've switched away from using the `pg` gem in Hanlon and are now using the `jdbc-postgres` gem instead to provide support for the use of PostgreSQL as a backing store in Hanlon. This shift was made because one of the deployment mechanisms we support in Hanlon is to deploy the server as a WAR file to a Java application server or servlet engine (like JBoss or Tomcat), and to do so we have to run the application under JRuby (so no native extensions are allowed).

That being said, I have not personally tested the use of PostgreSQL as a backing store for Hanlon, so I can't speak to any other specific issues that may or may not exist. There are, however, others who have (like @sankarvema); so if you run into any other issues (after switching your `persist_mode` to `postgres`)?

**Comment by toepi** [comment]
Oh sorry I've not see this typo. But migration to jdbc-postgres is not finish see Issue #245.

**Comment by tjmcs** [comment]
Agreed; as I said earlier I'm fairly sure that most of the testing that has been done to date has been MongoDB-based. If you (or any other PostgreSQL users) would like to try to sort through the remaining problems that resulted in @sankarvema filing Issue #245, I'm sure there are many others who would appreciate the fixes/improvements. I will also ping @sankarvema offline to see if he's been able to make any progress on Issue #245...my guess, however, is that he has not been able to dedicate any time to it since he filed that issue.

**Comment by altman87120** [comment]
Hi! After I change，my persist_mode to postgres the error also append

**Comment by tjmcs** [comment]
related to the old, JRuby-based version of Hanlon, so no longer applicable
