### ISSUE TITLE
pxe or ipxe, is this a question?

### ISSUE THREAD

**Issue by cizixs** [csc/Hanlon#341]
I know that `hanlon` uses `ipxe` as an extend of `pxe` to support http boot and other features.

While using ipxe, we encountered some problems. The biggest one is UEFI, server with UEFI instead of BIOS tends to have trouble booting from ipxe defined in `hanlon`. This is also mentioned in [ipxe official post](http://ipxe.org/efi/vision), looks like they're working on this.

So we decide to change ipxe back to pxe, which is an ongoing task. The main idea to use pxe pxelinux.cfg booting order, and dynamically create mac-address-named boot script when an active_model is added to a node.

By doing this, we have to change how `hanlon` manages image. Instead of centralizing image add/update/delete, all images should placed under tftfboot/ directory, because http boot is unavailable.

My question here is: Why did `hanlon` choose ipxe at the first place(I failed to find any clarification)? And is there a better way to solve ipxe/UEFI problem?

**Comment by tjmcs** [comment]
Hi @cizixs; we used iPXE in Razor/Hanlon because it was much easier to manage than PXE. Since iPXE is HTTP/HTTPS based, it was much easier to dynamically add/remove images that we are serving up through Hanlon than if we were trying to do the same thing via PXE. In a PXE-based server, we'd be modifying not only the directory structure if we wanted to add/remove new OS/Hypervisor images, but we'd also have to modify the menu used with the PXE-based server to coincide with the new directory structure (and somehow ensure that the right menu option was automatically chosen for a given server during the server boot process). With iPXE, all of that is reduced to serving up an iPXE-boot script from Hanlon (in response to an HTTP request) that has been customized for a given server.

So, that's why we chose to base Razor/Hanlon on iPXE in the first place. I know there are some issues with some network cards and chain booting (from PXE to iPXE), but I'm not aware of cards that have issues with iPXE-booting itself. Is the problem you're talking about a chain-booting problem or an iPXE-booting problem? If the former, we do have a workaround for cards with those sorts of issues documented [here](https://github.com/csc/Hanlon/wiki/Alternate-PXE-boot-options) (look under the first section, which documents how to skip the "PXE-bypass menu" and boot straight into an iPXE-boot against the Hanlon server).

Hopefully this helps. Please do let me know whether or not this response closes out this issue or not...

**Comment by tjmcs** [comment]
has not been updated in nearly a year and have not had a response from the user who opened it, so closing for now
