### ISSUE TITLE
coreos_in_memory stays in init state, even when it's up with no broker

### ISSUE THREAD

**Issue by hh** [csc/Hanlon#363]
The machine is up, and I can ssh into it, however it never get's beyond the ```init``` state.

```
$ hanlon active_model 5qR logs

State   Action                   Result                   Time     Last     Total            Node           
init   mk_call    n/a                                   05:39:25  0 sec    0 sec    2Js9jJ2FVw47MlwRTfxJWK  
init   boot_call  Starting CoreOS In-Memory model boot  05:40:43  1.3 min  1.3 min  2Js9jJ2FVw47MlwRTfxJWK  
```

I suggest we do something similar to the coreos_stable, where we call the callback to progress and save our state.

https://github.com/csc/Hanlon/blob/master/core/model/coreos/cloud-config.erb#L12
```
sudo coreos-install -d <%= install_disk %> -c /tmp/cloud-config.yaml
[ "$?" -eq 0 ] && curl <%= callback_url("postinstall", "complete") %> || curl <%= callback_url("postinstall", "install_fail") %>
```

**Comment by tjmcs** [comment]
I was torn about this one; obviously I could make a callback to change the state to `complete`, but the OS really is never completely installed when you're booting into an in-memory OS. At any time, you could reboot the machine and the OS instance you're working with would be removed. As such, I decided to leave the OS in an `init` state (which is were it is...booted into the in-memory OS with nothing installed on disk) and not move it to the `complete` state.

There is precedent for this; the same `init` state is where the `discover_only` model is left after a node is discovered (for example). In any event, I'm open to discussing this further, but leaving the state in an `init` state when the in-memory OS completed booting was by design, not an oversight...

**Comment by hh** [comment]
The OS install is complete when hanlon can hand it over to an optional broker.
A broker can't take over if we don't reach complete.

**Comment by hh** [comment]
Discover only... sorta makes sense, but the discovery is complete. I think the active_model should show all the relevant steps. Allows nice UI's as well to show progress. If we only go part way for some it will make developing interfaces a bit clunky.

**Comment by tjmcs** [comment]
I see your point, @hh; will see what I can do...I think I see a path forward using a combination of the current `cloud_config` that we're passing to the CoreOS instance as it boots, with a bit of the `write_files` and  `coreos['units']` configuration parameters mixed in to handle the callback we'll need to transition to a `complete` state once the machine finishes booting up into CoreOS in memory. It will also require some changes to the FSM to handle reboots. Long story short, probably something I should tackle when I'm a bit less tired from a long day, so I'll take a deeper look at it in the morning.

That being said, I don't think we've even thought about how a proper broker handoff would work with CoreOS (whether in memory or on disk). To date, those models/policies are in the same place we're at with respect to Windows instances; the code for a broker handoff really doesn't exist (even though the ability to define a broker for a policy that binds a model of one of these three types still exists)...just a bit of food for thought.
